name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.18'

    - name: Install flake8
      run: pip install flake8

    - name: Install Dependencies
      run: pip install -r requirements.txt

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Lint
      run: |
        python3.8.18 -m flake8 --select=E20,E21,E22,E23,E24,E3,F401,F8 --ignore=E226

    - name: Run Tests
      run: pytest

  package:
    name: Package
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Package Application
      run: echo "Packaging application..."

  deploy:
    name: Deploy
    needs: package
    runs-on: ubuntu-latest

    steps:
    - name: Package Application
      run: echo "Deploying application..."